core = 7.x
api = 2

; Include ding2 make file
includes[ding2] = "ding2.make"

; easyOPAC modules
projects[ding_billetexpressen_import][type]             = "module"
projects[ding_billetexpressen_import][subdir]           = ""
projects[ding_billetexpressen_import][download][type]   = "git"
projects[ding_billetexpressen_import][download][url]    = "git@github.com:easySuite/ding_billetexpressen_import.git"
projects[ding_billetexpressen_import][download][tag]    = "7.x-4.2.1"
;projects[ding_billetexpressen_import][download][branch] = "development"

projects[ding_billettendk_import][type]             = "module"
projects[ding_billettendk_import][subdir]           = ""
projects[ding_billettendk_import][download][type]   = "git"
projects[ding_billettendk_import][download][url]    = "git@github.com:easySuite/ding_billettendk_import.git"
projects[ding_billettendk_import][download][tag]    = "7.x-4.0.2"
;projects[ding_billettendk_import][download][branch] = "development"

projects[ding_blog][type]             = "module"
projects[ding_blog][subdir]           = ""
projects[ding_blog][download][type]   = "git"
projects[ding_blog][download][url]    = "git@github.com:easySuite/ding_blog.git"
projects[ding_blog][download][tag]    = "7.x-4.2.1"
;projects[ding_blog][download][branch] = "development"

projects[ding_calendar][type]             = "module"
projects[ding_calendar][subdir]           = ""
projects[ding_calendar][download][type]   = "git"
projects[ding_calendar][download][url]    = "git@github.com:easySuite/ding_calendar.git"
projects[ding_calendar][download][tag]    = "7.x-4.0.2"
;projects[ding_calendar][download][branch] = "development"

projects[ding_context_search][type]             = "module"
projects[ding_context_search][subdir]           = ""
projects[ding_context_search][download][type]   = "git"
projects[ding_context_search][download][url]    = "git@github.com:easySuite/ding_context_search.git"
projects[ding_context_search][download][tag]    = "7.x-3.0.2"
;projects[ding_context_search][download][branch] = "development"

projects[ding_easyscreen_teaser][type]             = "module"
projects[ding_easyscreen_teaser][subdir]           = ""
projects[ding_easyscreen_teaser][download][type]   = "git"
projects[ding_easyscreen_teaser][download][url]    = "git@github.com:easySuite/ding_easyscreen_teaser.git"
projects[ding_easyscreen_teaser][download][tag]    = "7.x-4.1.0"
;projects[ding_easyscreen_teaser][download][branch] = "development"

projects[ding_event_calendar][type]             = "module"
projects[ding_event_calendar][subdir]           = ""
projects[ding_event_calendar][download][type]   = "git"
projects[ding_event_calendar][download][url]    = "git@github.com:easySuite/ding_event_calendar.git"
;projects[ding_event_calendar][download][tag]    = "7.x-4.2.1"
projects[ding_event_calendar][download][branch] = "develop-culture"

projects[ding_event_clone][type]             = "module"
projects[ding_event_clone][subdir]           = ""
projects[ding_event_clone][download][type]   = "git"
projects[ding_event_clone][download][url]    = "git@github.com:easySuite/ding_event_clone.git"
projects[ding_event_clone][download][tag]    = "7.x-4.2.1"
;projects[ding_event_clone][download][branch] = "development"

projects[ding_event_subscriptions][type]             = "module"
projects[ding_event_subscriptions][subdir]           = ""
projects[ding_event_subscriptions][download][type]   = "git"
projects[ding_event_subscriptions][download][url]    = "git@github.com:easySuite/ding_event_subscriptions.git"
projects[ding_event_subscriptions][download][tag]    = "7.x-4.0.2"
;projects[ding_event_subscriptions][download][branch] = "master"

projects[ding_event_rooms][type]             = "module"
projects[ding_event_rooms][subdir]           = ""
projects[ding_event_rooms][download][type]   = "git"
projects[ding_event_rooms][download][url]    = "git@github.com:easySuite/ding_event_rooms.git"
projects[ding_event_rooms][download][tag]    = "7.x-4.2.1"
;projects[ding_event_rooms][download][branch] = "development"

projects[ding_header_opening_hours][type]             = "module"
projects[ding_header_opening_hours][subdir]           = ""
projects[ding_header_opening_hours][download][type]   = "git"
projects[ding_header_opening_hours][download][url]    = "git@github.com:easySuite/ding_header_opening_hours.git"
projects[ding_header_opening_hours][download][tag]    = "7.x-4.0.2"
;projects[ding_header_opening_hours][download][branch] = "development"

projects[ding_item_list][type]             = "module"
projects[ding_item_list][subdir]           = ""
projects[ding_item_list][download][type]   = "git"
projects[ding_item_list][download][url]    = "git@github.com:easySuite/ding_item_list.git"
projects[ding_item_list][download][tag]    = "7.x-4.2.1"
;projects[ding_item_list][download][branch] = "development"

projects[ding_kultunaut_import][type]             = "module"
projects[ding_kultunaut_import][subdir]           = ""
projects[ding_kultunaut_import][download][type]   = "git"
projects[ding_kultunaut_import][download][url]    = "git@github.com:easySuite/ding_kultunaut_import.git"
projects[ding_kultunaut_import][download][tag]    = "7.x-4.2.1"
;projects[ding_kultunaut_import][download][branch] = "development"

projects[ding_library_opening_hours][type]             = "module"
projects[ding_library_opening_hours][subdir]           = ""
projects[ding_library_opening_hours][download][type]   = "git"
projects[ding_library_opening_hours][download][url]    = "git@github.com:easySuite/ding_library_opening_hours.git"
projects[ding_library_opening_hours][download][tag]    = "7.x-4.1.1"
;projects[ding_library_opening_hours][download][branch] = "development"

projects[ding_menu_alt][type]             = "module"
projects[ding_menu_alt][subdir]           = ""
projects[ding_menu_alt][download][type]   = "git"
projects[ding_menu_alt][download][url]    = "git@github.com:easySuite/ding_menu_alt.git"
projects[ding_menu_alt][download][tag]    = "7.x-4.1.0"
;projects[ding_menu_alt][download][branch] = "development"

projects[ding_nis][type]             = "module"
projects[ding_nis][subdir]           = ""
projects[ding_nis][download][type]   = "git"
projects[ding_nis][download][url]    = "git@github.com:easySuite/ding_nis.git"
projects[ding_nis][download][tag]    = "7.x-4.2.1"
;projects[ding_nis][download][branch] = "development"

projects[ding_nodelist][type]             = "module"
projects[ding_nodelist][subdir]           = ""
projects[ding_nodelist][download][type]   = "git"
projects[ding_nodelist][download][url]    = "git@github.com:easySuite/ding_nodelist.git"
;projects[ding_nodelist][download][tag]    = "7.x-4.2.1"
projects[ding_nodelist][download][branch] = "culture-development"

projects[ding_redia_rss][type]             = "module"
projects[ding_redia_rss][subdir]           = ""
projects[ding_redia_rss][download][type]   = "git"
projects[ding_redia_rss][download][url]    = "git@github.com:easySuite/ding_redia_rss.git"
projects[ding_redia_rss][download][tag]    = "7.x-4.1.0"
;projects[ding_redia_rss][download][branch] = "develop"

projects[ding_redia_variables][type]             = "module"
projects[ding_redia_variables][subdir]           = ""
projects[ding_redia_variables][download][type]   = "git"
projects[ding_redia_variables][download][url]    = "git@github.com:easySuite/ding_redia_variables.git"
projects[ding_redia_variables][download][tag]    = "7.x-4.2.1"
;projects[ding_redia_variables][download][branch] = "development"

projects[ding_related_content_search][type]             = "module"
projects[ding_related_content_search][subdir]           = ""
projects[ding_related_content_search][download][type]   = "git"
projects[ding_related_content_search][download][url]    = "git@github.com:easySuite/ding_related_content_search.git"
projects[ding_related_content_search][download][tag]    = "7.x-4.2.1"
;projects[ding_related_content_search][download][branch] = "development"

projects[ding_social][type]             = "module"
projects[ding_social][subdir]           = ""
projects[ding_social][download][type]   = "git"
projects[ding_social][download][url]    = "git@github.com:easySuite/ding_social.git"
projects[ding_social][download][tag]    = "7.x-4.2.1"
;projects[ding_social][download][branch] = "development"

projects[ding_video][type]             = "module"
projects[ding_video][subdir]           = ""
projects[ding_video][download][type]   = "git"
projects[ding_video][download][url]    = "git@github.com:easySuite/ding_video.git"
projects[ding_video][download][tag]    = "7.x-3.0.2"
;projects[ding_video][download][branch] = "development"

projects[easyddb_facebookshare][type]             = "module"
projects[easyddb_facebookshare][subdir]           = ""
projects[easyddb_facebookshare][download][type]   = "git"
projects[easyddb_facebookshare][download][url]    = "git@github.com:easySuite/easyddb_facebookshare.git"
projects[easyddb_facebookshare][download][tag]    = "7.x-4.0.2"
;projects[easyddb_facebookshare][download][branch] = "development"

projects[easyddb_dams][type]             = "module"
projects[easyddb_dams][subdir]           = ""
projects[easyddb_dams][download][type]   = "git"
projects[easyddb_dams][download][url]    = "git@github.com:easySuite/easyddb_dams.git"
projects[easyddb_dams][download][tag]    = "7.x-4.2.1"
;projects[easyddb_dams][download][branch] = "development"

projects[easyddb_direct_link][type]             = "module"
projects[easyddb_direct_link][subdir]           = ""
projects[easyddb_direct_link][download][type]   = "git"
projects[easyddb_direct_link][download][url]    = "git@github.com:easySuite/easyddb_direct_link.git"
projects[easyddb_direct_link][download][tag]    = "7.x-4.0.2"
;projects[easyddb_direct_link][download][branch] = "development"

projects[easyddb_editorial_base][type]             = "module"
projects[easyddb_editorial_base][subdir]           = ""
projects[easyddb_editorial_base][download][type]   = "git"
projects[easyddb_editorial_base][download][url]    = "git@github.com:easySuite/easyddb_editorial_base.git"
projects[easyddb_editorial_base][download][tag]    = "7.x-4.2.1"
;projects[easyddb_editorial_base][download][branch] = "development"

projects[easyddb_extlink_settings][type]             = "module"
projects[easyddb_extlink_settings][subdir]           = ""
projects[easyddb_extlink_settings][download][type]   = "git"
projects[easyddb_extlink_settings][download][url]    = "git@github.com:easySuite/easyddb_extlink_settings.git"
projects[easyddb_extlink_settings][download][tag]    = "7.x-4.0.2"
;projects[easyddb_extlink_settings][download][branch] = "development"

projects[easyddb_frontend_layout][type]             = "module"
projects[easyddb_frontend_layout][subdir]           = ""
projects[easyddb_frontend_layout][download][type]   = "git"
projects[easyddb_frontend_layout][download][url]    = "git@github.com:easySuite/easyddb_frontend_layout.git"
projects[easyddb_frontend_layout][download][tag]    = "7.x-4.1.0"
;projects[easyddb_frontend_layout][download][branch] = "development"

projects[easyddb_smartbanner][type]             = "module"
projects[easyddb_smartbanner][subdir]           = ""
projects[easyddb_smartbanner][download][type]   = "git"
projects[easyddb_smartbanner][download][url]    = "git@github.com:easySuite/easyddb_smartbanner.git"
projects[easyddb_smartbanner][download][tag]    = "7.x-4.1.0"
;projects[easyddb_smartbanner][download][branch] = "development"

projects[easyddb_search_radios][type]             = "module"
projects[easyddb_search_radios][subdir]           = ""
projects[easyddb_search_radios][download][type]   = "git"
projects[easyddb_search_radios][download][url]    = "git@github.com:easySuite/easyddb_search_radios.git"
projects[easyddb_search_radios][download][tag]    = "7.x-4.0.2"
;projects[easyddb_search_radios][download][branch] = "development"

projects[easyddb_xml_events][type]             = "module"
projects[easyddb_xml_events][subdir]           = ""
projects[easyddb_xml_events][download][type]   = "git"
projects[easyddb_xml_events][download][url]    = "git@github.com:easySuite/easyddb_xml_events.git"
projects[easyddb_xml_events][download][tag]    = "7.x-4.2.1"
;projects[easyddb_xml_events][download][branch] = "development"

projects[easyddb_zerohit_redirect][type]             = "module"
projects[easyddb_zerohit_redirect][subdir]           = ""
projects[easyddb_zerohit_redirect][download][type]   = "git"
projects[easyddb_zerohit_redirect][download][url]    = "git@github.com:easySuite/easyddb_zerohit_redirect.git"
projects[easyddb_zerohit_redirect][download][tag]    = "7.x-4.0.2"
;projects[easyddb_zerohit_redirect][download][branch] = "development"

projects[emailkanon][type]             = "module"
projects[emailkanon][subdir]           = ""
projects[emailkanon][download][type]   = "git"
projects[emailkanon][download][url]    = "git@github.com:easySuite/emailkanon.git"
projects[emailkanon][download][tag]    = "7.x-3.0.0"
;projects[emailkanon][download][branch] = "development"

projects[kultunaut_events][type]             = "module"
projects[kultunaut_events][subdir]           = ""
projects[kultunaut_events][download][type]   = "git"
projects[kultunaut_events][download][url]    = "git@github.com:easySuite/kultunaut_events.git"
projects[kultunaut_events][download][tag]    = "7.x-4.0.2"
;projects[kultunaut_events][download][branch] = "development"

projects[ting_covers_backside][type]             = "module"
projects[ting_covers_backside][subdir]           = ""
projects[ting_covers_backside][download][type]   = "git"
projects[ting_covers_backside][download][url]    = "git@github.com:easySuite/ting_covers_backside.git"
projects[ting_covers_backside][download][tag]    = "7.x-4.2.1"
;projects[ting_covers_backside][download][branch] = "development"

projects[ting_covers_plus][type]             = "module"
projects[ting_covers_plus][subdir]           = ""
projects[ting_covers_plus][download][type]   = "git"
projects[ting_covers_plus][download][url]    = "git@github.com:easySuite/ting_covers_plus.git"
projects[ting_covers_plus][download][tag]    = "7.x-3.1.0"
;projects[ting_covers_plus][download][branch] = "development"

projects[ting_reference_advanced][type]              = "module"
projects[ting_reference_advanced][subdir]            = ""
projects[ting_reference_advanced][download][type]    = "git"
projects[ting_reference_advanced][download][url]     = "git@github.com:easySuite/ting_reference_advanced.git"
projects[ting_reference_advanced][download][tag]     = "7.x-4.2.1"
;projects[ting_reference_advanced][download][branch]  = "development"

projects[ting_titles_decoration][type]             = "module"
projects[ting_titles_decoration][subdir]           = ""
projects[ting_titles_decoration][download][type]   = "git"
projects[ting_titles_decoration][download][url]    = "git@github.com:easySuite/ting_titles_decoration.git"
projects[ting_titles_decoration][download][tag]    = "7.x-4.0.2"
;projects[ting_titles_decoration][download][branch] = "development"


; KulturØen.dk repositories
projects[kultur_calendar][type]             = "module"
projects[kultur_calendar][subdir]           = ""
projects[kultur_calendar][download][type]   = "git"
projects[kultur_calendar][download][url]    = "git@github.com:easySuite/kultur_calendar.git"
projects[kultur_calendar][download][branch] = "development"

projects[kultur_events][type]             = "module"
projects[kultur_events][subdir]           = ""
projects[kultur_events][download][type]   = "git"
projects[kultur_events][download][url]    = "git@github.com:easySuite/kultur_events.git"
projects[kultur_events][download][branch] = "development"

projects[kultur_frontpage][type]             = "module"
projects[kultur_frontpage][subdir]           = ""
projects[kultur_frontpage][download][type]   = "git"
projects[kultur_frontpage][download][url]    = "git@github.com:easySuite/kultur_frontpage.git"
projects[kultur_frontpage][download][branch] = "development"

projects[kultur_subtheme][type]             = "theme"
projects[kultur_subtheme][subdir]           = ""
projects[kultur_subtheme][download][type]   = "git"
projects[kultur_subtheme][download][url]    = "git@github.com:easySuite/kultur_subtheme.git"
projects[kultur_subtheme][download][branch] = "develop"

projects[ding_language][type]             = "module"
projects[ding_language][subdir]           = ""
projects[ding_language][download][type]   = "git"
projects[ding_language][download][url]    = "git@github.com:easySuite/ding_language.git"
projects[ding_language][download][tag]    = "7.x-4.2.1"
;projects[ding_language][download][branch] = "development"

