<?php

/**
 * @file
 * Setup the fields needed for ding list.
 */

/**
 * Delete ding_entity_rating_popular_on_frontpage variable
 */
function ding_entity_rating_update_7001() {
  variable_del('ding_entity_rating_popular_on_frontpage');
}

/**
 * Remove "ding_entity_rating_result" field from database.
 */
function ding_entity_rating_update_7002() {
  field_delete_field('ding_entity_rating_result');
  field_purge_batch(1);
}
